import "../styles/globals.css";
import "../styles/carousel.css";
import { ProductsProvider } from "../components/productContext";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import store from "../Redux/Store";
import { Provider } from "react-redux";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { SessionProvider } from "next-auth/react";

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  return (
    <>
      <Head>
        <title>G.O.A.T Digital | Online digital shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />

        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Provider store={store}>
        <SessionProvider session={session} basePath="/api/auth">
          <Header />
          <ProductsProvider>
            <Component {...pageProps} />
            <ToastContainer />
          </ProductsProvider>
        </SessionProvider>
      </Provider>
      <Footer />;
    </>
  );
}
